[package]
name = "death-to-the-pixels"
version = "0.1.0"
authors = ["rvuong"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
imap = "2.0.2"
native-tls = "0.2.4"
