version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_dev
    volumes:
      - .:/app
    ports:
      - ${ROCKET_PORT}:${ROCKET_PORT}
    networks:
      - rust
    environment:
      - ROCKET_ADDRESS=${ROCKET_ADDRESS}
      - ROCKET_PORT=${ROCKET_PORT}
      - IMAP_HOST=${IMAP_HOST}
      - IMAP_USERNAME=${IMAP_USERNAME}
      - IMAP_PASSWORD=${IMAP_PASSWORD}
      - IMAP_PORT=${IMAP_PORT}

networks:
  rust:
