version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_dev
    volumes:
      - .:/app
    ports:
      - ${ROCKET_PORT}:${ROCKET_PORT}
    networks:
      - rust
    environment:
      - DEBUG=${DEBUG}
      - RUST_LOG=${RUST_LOG}
      - IMAP_HOST=${IMAP_HOST}
      - IMAP_USERNAME=${IMAP_USERNAME}
      - IMAP_PASSWORD=${IMAP_PASSWORD}
      - IMAP_PORT=${IMAP_PORT}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SENDER=${SMTP_SENDER}

networks:
  rust:
